export const tables = [
  `CREATE TABLE IF NOT EXISTS conversations (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    channel TEXT NOT NULL,
    channel_conversation_id TEXT,
    customer_name TEXT,
    customer_email TEXT,
    customer_phone TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    sentiment TEXT DEFAULT 'neutral',
    lead_status TEXT,
    assigned_to TEXT,
    escalated_to TEXT,
    escalation_reason TEXT,
    is_sales_mode INTEGER DEFAULT 0,
    message_preview TEXT,
    unread_count INTEGER DEFAULT 0,
    last_activity_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    last_synced_at TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS messages (
    id TEXT PRIMARY KEY,
    conversation_id TEXT NOT NULL,
    organization_id TEXT NOT NULL,
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    sentiment TEXT,
    confidence_score REAL,
    metadata TEXT,
    created_at TEXT NOT NULL,
    last_synced_at TEXT,
    FOREIGN KEY (conversation_id) REFERENCES conversations(id)
  )`,
  `CREATE TABLE IF NOT EXISTS leads (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    conversation_id TEXT,
    name TEXT,
    email TEXT,
    phone TEXT,
    product_interest TEXT,
    budget TEXT,
    source TEXT,
    status TEXT NOT NULL DEFAULT 'new',
    assigned_to TEXT,
    synced_to_crm INTEGER DEFAULT 0,
    notes TEXT,
    score REAL,
    created_at TEXT NOT NULL,
    updated_at TEXT,
    last_synced_at TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS escalations (
    id TEXT PRIMARY KEY,
    conversation_id TEXT NOT NULL,
    organization_id TEXT NOT NULL,
    triggered_by TEXT NOT NULL,
    reason TEXT,
    conversation_summary TEXT,
    issue_summary TEXT,
    resolved_by TEXT,
    resolved_at TEXT,
    status TEXT DEFAULT 'open',
    created_at TEXT NOT NULL,
    last_synced_at TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL,
    full_name TEXT NOT NULL,
    avatar_url TEXT,
    phone TEXT,
    locale TEXT,
    timezone TEXT,
    last_synced_at TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS organizations (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL,
    logo_url TEXT,
    is_active INTEGER DEFAULT 1,
    status TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT,
    last_synced_at TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS pending_operations (
    id TEXT PRIMARY KEY,
    operation TEXT NOT NULL,
    table_name TEXT NOT NULL,
    record_id TEXT NOT NULL,
    payload TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    retry_count INTEGER DEFAULT 0,
    error TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages(conversation_id)`,
  `CREATE INDEX IF NOT EXISTS idx_conversations_org ON conversations(organization_id)`,
  `CREATE INDEX IF NOT EXISTS idx_conversations_status ON conversations(status)`,
  `CREATE INDEX IF NOT EXISTS idx_leads_org ON leads(organization_id)`,
  `CREATE INDEX IF NOT EXISTS idx_escalations_org ON escalations(organization_id)`,
  `CREATE INDEX IF NOT EXISTS idx_pending_ops_status ON pending_operations(status)`,
]
